name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    #- name: Build release APK
     # run: ./gradlew assembleRelease
    - name: Restore keystore
      run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > app/strong_intern.jks

    - name: Generate key.properties
      run: |
        
        {
          echo "storeFile=app/strong_intern.jks";
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}";
          echo "keyAlias=${{ secrets.KEY_ALIAS }}";
          echo "keyPassword=${{ secrets.ALIAS_PASSWORD }}";
        } > key.properties

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Clean up sensitive files
      run: rm -f key.properties
